title: vortezwohl's blog
description: vortezwohl's blog
author: vortezwohl
avatar: /logo.png
email: vortez.wohl@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 6
baseurl: ""

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: vortezwohl
  card: summary
logo: logo.png
social:
  name: vortezwohl
  links:
    - https://github.com/vortezwohl
    - https://linkedin.com/in/vortez-wohl-677225353
    - https://twitter.com/vortezwohl
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
